package_assets: on # (on, off, always)
embed_assets: on # (on, off, datauri)
compress_assets: off # (on, off)
gzip_assets: on # (on, off)
javascripts:

workspace:
    - public/javascripts/*.js

stylesheets:
  common:
    - public/stylesheets/*.css

