defaults: &defaults

development:
  <<: *defaults
  host: localhost
  database: grbr_development

test:
  <<: *defaults
  host: localhost
  database: grbr_test

production:
  <<: *defaults
  host: localhost
  database: grbr_production


