defaults: &defaults
  #host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  host: localhost
  database: grbr_development

test:
  <<: *defaults
  host: localhost
  database: grbr_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

  #host: http://test-grabr-app.heroku.com/
  database: grbr_production
