production:
  sessions:
    default:
      database: grbr_production
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        raise_not_found_error: false
development:
  sessions:
    default:
      database: grbr_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        raise_not_found_error: false    